CREATE OR REPLACE PROCEDURE SP_EMPLOYEE_100(P_ID_EMPLOYEE IN NUMBER,
                                            P_VL_SALARY   OUT NUMBER) IS
    V_SALARY EMPLOYEES.SALARY%TYPE;

    CURSOR CUR_RET_SALARY (P_EMPLYEE_ID NUMBER) IS
       SELECT SALARY FROM EMPLOYEES
       WHERE EMPLOYEE_ID = P_EMPLYEE_ID;

BEGIN
    
    UPDATE EMPLOYEES
       SET SALARY = SALARY + 100
       WHERE EMPLOYEE_ID = P_ID_EMPLOYEE;

       
    OPEN CUR_RET_SALARY (P_ID_EMPLOYEE);
    FETCH CUR_RET_SALARY INTO V_SALARY;
    CLOSE CUR_RET_SALARY;
    
    P_VL_SALARY := V_SALARY;

EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('OCORREU UM ERRO!!');
END;
/
